server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/estoque/ {
        proxy_pass http://estoque:8080/;
    }

    location /api/faturamento/ {
        proxy_pass http://faturamento:8080/;
    }
}
