services:
  estoque:
    build: ./backend/Estoque
    environment:
      ConnectionStrings__Default: Data Source=/dados/estoque.db
      Ia__BaseUrl: http://ollama:11434
      Ia__Modelo: llama3.2:1b
    depends_on:
      - ollama
    volumes:
      - estoque-dados:/dados

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama

  ollama-pull:
    image: ollama/ollama
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["ollama", "pull", "llama3.2:1b"]
    restart: on-failure

  faturamento:
    build: ./backend/Faturamento
    environment:
      ConnectionStrings__Default: Data Source=/dados/faturamento.db
      Estoque__BaseUrl: http://estoque:8080
    volumes:
      - faturamento-dados:/dados
    depends_on:
      - estoque

  frontend:
    build: ./frontend
    ports:
      - "9123:80"
    depends_on:
      - faturamento

volumes:
  ollama:
  estoque-dados:
  faturamento-dados:
